[[plugins]]
repo = 'tpope/vim-fugitive'
merged = 0

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if has('win32') || has('win64')
    call system('tools\update-dll-mingw.bat')
elseif has('unix')
    call system('make')
endif
'''

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-scriptease'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'fweep/vim-tabber'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'PProvost/vim-ps1'

[[plugins]]
repo = 'interleaved/vim-pester'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0
on_if = 1

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'junegunn/fzf'
merged = 0
hook_post_update = '''
if IsWindows()
    call system('go get -u github.com/junegunn/fzf')
elseif has('unix')
    call system('./install --all')
endif
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
