[[plugins]]
repo = 'tpope/vim-fugitive'
merged = 0

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if IsWindows()
    call system('tools\update-dll-mingw.bat')
elseif has('unix')
    call system('make')
endif
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

# [[plugins]]
# repo  = 'kana/vim-repeat'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'fweep/vim-tabber'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'PProvost/vim-ps1'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# hook_post_update = '''
# system('yarn install')
# call coc#util#install()
# '''
# depends = 'neoclide/vim-node-rpc'
# on_ft = 'ps1'

# on_cmd = [
#     'Git', 'Git!', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull',
#     'Grebase', 'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit',
#     'Gsplit', 'Gvsplit', 'Gtabedit', 'Gpedit', 'Gsplit!', 'Gvsplit!',
#     'Gtabedit!', 'Gpedit!', 'Gread', 'Gread!', 'Gwrite', 'Gwq', 'Gwq!',
#     'Gdiff', 'Gsdiff', 'Gvdiff', 'Gmove', 'Grename', 'Gdelete', 'Gremove',
#     'Gblame', 'Gbrowse'
# ]

# on_map = {'n': '<Plug>'}
