"
" Christian’s .vimrc
"
"  Shamelessly stole most ideas from Shougo
"  https://github.com/Shougo/shougo-s-github.git
"

let g:vimdir = fnamemodify(expand('<sfile>'), ':h:h')

if &compatible
  set nocompatible
endif

function! s:source_rc(path, ...) abort
  " let use_global = get(a:000, 0, !has('vim_starting'))
  let abspath = resolve(g:vimdir . '/rc/' . a:path)
  " if !use_global
  "   execute 'source' fnameescape(abspath)
  "   return
  " endif

  " substitute all 'set' to 'setglobal'
  let content = map(readfile(abspath),
        \ 'substitute(v:val, "^\\W*\\zsset\\ze\\W", "setglobal", "")')
  " create tempfile and source the tempfile
  let tempfile = tempname()
  try
    call writefile(content, tempfile)
    execute 'source' fnameescape(tempfile)
  finally
    if filereadable(tempfile)
      call delete(tempfile)
    endif
  endtry
endfunction

augroup MyAutoCmd
  autocmd!
  autocmd FileType,Syntax,BufNewFile,BufNew,BufRead *?
    \ call vimrc_ca#on_filetype()
  autocmd CursorHold *.toml syntax sync minlines=300
augroup END

if has('vim_starting')
  call s:source_rc('init.rc.vim')
endif

call s:source_rc('dein.rc.vim')

if has('vim_starting') && !empty(argv())
  call vimrc_ca#on_filetype()
endif

if !has('vim_starting')
  call dein#call_hook('source')
  call dein#call_hook('post_source')

  syntax enable
  filetype plugin indent on
endif



call s:source_rc('encoding.rc.vim')

" call s:source_rc('options.rc.vim')

call s:source_rc('mappings.rc.vim')


if IsWindows()
  call s:source_rc('windows.rc.vim')
else
  call s:source_rc('unix.rc.vim')
endif

if !has('nvim') && has('gui_running')
  call s:source_rc('gui.rc.vim')
endif


